export interface IHouseFinance {
    ten: string,
    tongGiaTri: number,
    laiVay: number,
    tiLeVay: number,
    thoiGianVay: number,
    thoiGianBan: number,
    tiLeBan: number,
    laiPhatTraTruoc: number,
    tienTraBanDau?: number,
    tienTraHangThang?: number,
    tienBan?: number,
    tienGocDaTra?: number,
    tongGocConlai?: number,
    tienLaiDaTra?: number,
    tongTienVay?: number,
    tongTienDaTra?: number,
    tienConPhaiTra?: number,
    tongThu?: number,
    tongTra?: number,
    laiLo?: number,
}
